export const ExpenseSheetTableHeaders = [
    "S.no",
    "Movie Name",
    "Location",
    "Date",
    "Crew Name",
    "Category",
    "Subcategory",
    "Number of Persons",
    "Advance",
    "Beta",
    "Actions",
  ];
  
 
 
  
  export const ExpenseSheetTableVaues = [
    {
      "Sno": "1",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
      
    },
    {
      "Sno": "2",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "3",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "4",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "S.no": "5",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "6",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "7",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "8",
      "MovieName": "Thalaiva",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "9",
      "MovieName": "raja",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "10",
      "MovieName": "Gilli",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "11",
      "MovieName": "Billa",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "12",
      "MovieName": "singam",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    {
      "Sno": "13",
      "MovieName": "Thuppaki",
      "Location":"Chennai",
      "date":"19/10/2024",
      "CrewName":"raja",
      "Category":"jggjhkjkjk",
      "SubCategory":"jgjhjhkjkj",
      "NumberofPersons": "10",
      "Advance":"50000",
      "Beta":"1000",
    },
    
  ];